project:
  type: website  


website:
  title: "Chicago Public Health PONs Project"
  navbar:
    search: true
    right:
      - text: "Home"
        file: index.qmd
      - text: "Our Team"
        file: Ourteam.qmd
      - text: "Project Information"
        file: ProjectInformation.qmd
      - text: "Findings"
        file: Findings.qmd
      - text: "Connect with Us"
        file: Connect.qmd
format:
  html:
    theme: flatly
    toc: true
    toc-depth: 2