project:
  type: website

website:
  title: "Chicago-Health-PONs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Our Team"
        file: Ourteam.qmd
      - text: "Project Information"
        file: ProjectInformation.qmd
      - text: "Findings"
        file: Findings.qmd
      - text: "Connect with Us"
        file: Connect.qmd

format:
  html:
    theme: 
     light: flatly
     dark: darkly
    toc: true
    toc-depth: 2

editor: visual

