---
title: " "
format: html
---

## Project Information

As of March 2024, our team of researchers in UIC’s Networks and Governance Lab have identified over 65 community health and wellness collaborative groups in the City of Chicago and Cook County, involving over 800 public and private sector organizations. These groups, referred to here as purpose-oriented networks (PONs), are essential to supporting the diverse health and wellness needs of our vibrant communities.

### Methods

This study uses a population-level dataset which includes all the purpose-oriented public health networks and their members in Chicago and Cook County. The list of all the networks is primarily identified by research team members based on the publicly available data from network websites and documents. Network member organizations and individuals and their roles in the network are also collected based on publicly available data.

#### Survey

The coordinator/manager of each network in the list is invited to participate in this study. Coordinators/managers are included in the study if they agree to participate and can provide the necessary data. In our study, we are asking for the following data from participants:

-   Level of participation from each member of the network.
-   Insights about the structure of the network.
-   Information about the networks leaders and funders.
-   Relationships between networks.

We appreciate your time taking our survey:

https://uic.ca1.qualtrics.com/jfe/form/SV_3z4xXtb0N1sIR3U
